### ISSUE TITLE
async example is broken.

### ISSUE THREAD

**Issue by jplatte** [raphlinus/crochet#27]
I just copy-pasted the async example into a new project and it seems to be broken. It spams

    ERROR [crochet::widget::single] Single-child widget was created with 3 children.

on stdout and only displays the label `current count: 0`.

**Comment by jplatte** [comment]
I copied the `Column::new` from the counter example, that seemed to fix it. I might submit a PR later to fix the async example.

**Comment by luleyleo** [comment]
Oops, seems like I forgot to update it. Packing it in a `Column` is the right thing to do :+1:
